name: Deployment Pipeline

on:
  push:
    branches:
      - main
      #para controlar cuando se hagan pull request a la rama
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    #accion traida del marketplace
    #clona nuestro proyecto en la MV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    #instalamos node traida del marketplace
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Intall dependencies
      - run: npm ci
        #asegura que el codigo que estas integrando es correcto
      - name: Lint
        run: npm run eslint
        #hacemos el build
      - name: build
        run: npm run build
        #Ejecutamos los test
      - name: Test
        run: npm test
        